name: rivy
description: Redesign of Rivy's onboarding screen.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1

  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  flutter_svg_test: ^1.0.3
  flutter_image_test_utils: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: DegularDisplay
      fonts:
        - asset: assets/fonts/DegularDisplay-Thin.otf
          weight: 100
        - asset: assets/fonts/DegularDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/DegularDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/DegularDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/DegularDisplay-SemiBold.otf
          weight: 600
        - asset: assets/fonts/DegularDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/DegularDisplay-Black.otf
          weight: 900
